# Generated by Django 5.2.4 on 2025-07-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='host',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='host',
            name='province',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='province',
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Outlet',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
