# Generated by Django 5.2.4 on 2025-07-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfos', '0002_remove_outlet_branch_remove_host_outlet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='region',
            table='regions',
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostinfos.region')),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostinfos.branch')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostinfos.province')),
            ],
        ),
    ]
