# Generated by Django 5.2.4 on 2025-07-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfos', '0003_province_alter_region_table_branch_outlet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='outlet',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='province',
            table='province',
        ),
    ]
