# Generated by Django 5.2.4 on 2025-07-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfos', '0004_alter_branch_options_alter_outlet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
        migrations.AlterModelTable(
            name='outlet',
            table='outlets',
        ),
        migrations.AlterModelTable(
            name='province',
            table='provinces',
        ),
    ]
