# Generated by Django 5.2.4 on 2025-07-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfos', '0005_alter_branch_table_alter_outlet_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outlet',
        ),
    ]
